version: "3.9"

services:
  db:
    image: postgres:17
    container_name: app-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AppDataBase

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Launcher/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ./HR-Department.APIv2 # Corrected
      dockerfile: ./HR-Department.APIv2/Dockerfile
    container_name: my-app
    restart: always
    ports:
      - "8000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=AppDataBase;Username=postgres;Password=postgres"

    depends_on:
      - db

volumes:
  db_data: